### ISSUE TITLE
Recreate Test set

### ISSUE THREAD

**Issue by marijnl** [KevinMusgrave/powerful-benchmarker#39]
I'm trying to recreate the split train/test exactly like in the experiment in raw python code.

These are my settings from `config_dataset.yaml`
```
split_manager:
  ClassDisjointSplitManager:
    test_size: 0.5
    test_start_idx: 0.5
    num_training_partitions: 4
    num_training_sets: 4
    hierarchy_level: 0
    data_and_label_getter_keys: null
```
Any (easy) way to do this?
I guess i would need to instantiate ClassDisjointSplitManager with the seed from the experiment but i dont know where i can find this info.
